# 딥러닝(0)
## NumPy
* Numerical Python: NumPy는 파이썬으로 수치 계산, 특히 ```다차원 배열(ndarray)```을 쉽고 빠르게 다루기 위해 만들어졌습니다.
* 성능: 내부적으로 C언어로 구현되어 있어 파이썬 기본 리스트보다 훨씬 빠르고 메모리를 효율적으로 사용합니다.
* 다양한 함수: 선형대수, 푸리에 변환, 난수 생성 등 과학/공학 계산에 필요한 다양한 수학 함수를 제공합니다.
* 생태계의 중심: Pandas, SciPy, Matplotlib, Scikit-learn 등 데이터 과학 및 머신러닝 라이브러리들이 NumPy 배열을 기본 데이터 구조로 사용합니다.

In [1]:
import numpy as np
print(f"NumPy 버전: {np.__version__}")

NumPy 버전: 1.26.4


### NumPy 배열(ndarray) 생성
NumPy의 핵심은 ndarray (N-dimensional array) 객체입니다. 다양한 방법으로 생성할 수 있습니다.

In [6]:
# 1차원 배열 (벡터)
list1 = [1, 2, 3, 4, 5]
A = np.array(list1)
A + 5         # 연산이 병렬적으로 가능

array([ 6,  7,  8,  9, 10])

In [8]:
# 2차원 배열 (행렬)
list2d = [[1, 2, 3], [4, 5, 6]]
A = np.array(list2d)
A * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
X = np.array([[2, 1]])     # 1행 2열의 2차원행렬 만든것
W = np.array([[1], [1]])     # 2행 1열의 2차원행렬
B = 1

# 행렬곱
X @ W + B       # 행렬곱은 골뱅이(@)로

array([[4]])

* 특정 값으로 채워진 배열 생성

In [14]:
# 모든 요소가 0인 배열 생성 (shape 지정)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# 모든 요소가 1인 배열 생성
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# 특정 값으로 채워진 배열 생성
np.full((2,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

* 연속된 값이나 특정 범위의 값으로 배열 생성

In [17]:
# 파이썬 range와 유사하지만 ndarray 반환
np.arange(0, 10, 0.1)          # range와 달리 증감값 소수로도 줄수있음 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [19]:
# 특정 구간을 균일하게 나눈 값으로 배열 생성
np.linspace(0, 1, 5)      # 0부터 1까지 균일한 5개로 나눠라

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* 난수 배열 생성

In [20]:
# 0과 1 사이의 균일 분포 난수 (shape 지정)
np.random.rand(2, 3)       # 2행 3열짜리 랜덤값을 가진 행렬 만듦

array([[0.66075758, 0.18050928, 0.98416739],
       [0.50791396, 0.59414775, 0.29962136]])

In [22]:
# 표준 정규 분포(평균 0, 표준편차 1) 난수
np.random.randn(2, 3)

array([[-0.10696076, -1.34425252,  1.22699819],
       [-0.65477154, -0.41654585,  0.99452593]])

In [25]:
# 특정 범위의 정수 난수
np.random.randint(1, 10, size = (2, 4))      # 10포함X.  (1부터 9까지)

array([[2, 2, 5, 6],
       [4, 3, 6, 6]])

### 배열의 속성 확인
생성된 ndarray 객체의 정보를 확인하는 것은 중요합니다.

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("샘플 배열:\n", arr)

샘플 배열:
 [[1 2 3]
 [4 5 6]]


In [27]:
# 배열의 형태 (shape): 각 차원의 크기를 튜플로 반환
arr.shape     # 2행3열 = 2차원

(2, 3)

In [28]:
# 배열의 차원 수 (ndim): 몇 차원 배열인지 정수 반환
arr.ndim

2

In [29]:
# 배열의 전체 요소 개수 (size)
arr.size

6

In [30]:
# 배열 요소의 데이터 타입 (dtype)
arr.dtype

dtype('int32')

In [37]:
# 데이터 타입을 지정하여 배열 생성 가능
# float_arr = np.array([1, 2, 3], dtype=np.float64)
float_arr = np.array([1, 2, 3], dtype="float")
float_arr

array([1., 2., 3.])

### 인덱싱(Indexing)과 슬라이싱(Slicing)
배열의 특정 요소나 부분을 선택하는 방법입니다. 딥러닝에서 데이터의 특정 부분을 추출하거나 조작할 때 매우 중요합니다.

* 기본 인덱싱

In [39]:
arr1d = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
print("1차원 배열:", arr1d, arr1d.ndim)

1차원 배열: [0 1 2 3 4 5 6 7 8 9] 1


In [42]:
#인덱싱도 가능
arr1d[-1]   

9

In [43]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2차원 배열:\n", arr2d)

2차원 배열:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# 특정 요소 접근: arr[행, 열]
arr2d[0, 0]        # 콤마를 기준으로 접근
arr2d[2, 2]    # 3행 3열 = 9

9

* 슬라이싱: ```:```을 사용하여 특정 범위를 선택합니다. [start:stop:step]

In [52]:
# 1차원 배열 슬라이싱
arr1d[:5]
arr1d[:]       # 처음부터 끝까지
arr1d[::2]     # 처음부터 끝까지 2씩 증가시키면서

array([0, 2, 4, 6, 8])

In [53]:
arr2d[:2, 1:3]   # 0열빼고 1열,2열만

array([[2, 3],
       [5, 6]])

In [54]:
# 첫 번째 행 전체
arr2d[0]

array([1, 2, 3])

In [56]:
# 두 번째 열 전체
arr2d[:, 1]    # 행은 모든행, 열은 1열

array([2, 5, 8])

* 불리언 인덱싱 (Boolean Indexing): 조건을 만족하는 요소만 선택합니다. 매우 강력한 기능입니다.

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[arr > 3]

array([4, 5, 6])

In [88]:
# 조건을 직접 사용 가능

In [64]:
# 2차원 배열에도 적용 가능  /  3보다 큰 요소 가져오기
arr2d = np.array([[1, 2], [3, 4], [5, 6]])
arr2d[arr2d > 3]         # 1차원 벡터

array([4, 5, 6])

### 배열 연산
NumPy 배열은 요소별(element-wise) 연산을 매우 효율적으로 수행합니다.

In [66]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)     # 행렬곱아니고 같은위치에있는것끼리 그냥 곱함
print(a / b)
print(a ** b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


* 스칼라 연산: 배열과 단일 값(스칼라) 간의 연산

In [67]:
arr = np.array([[1, 2], [3, 4]])
arr + 10

array([[11, 12],
       [13, 14]])

* 브로드캐스팅 (Broadcasting): NumPy가 다른 shape를 가진 배열 간의 연산을 가능하게 하는 강력한 메커니즘입니다. 특정 규칙에 따라 작은 배열이 큰 배열의 shape에 맞춰 확장되어 연산됩니다. (딥러닝에서 매우 중요!)

In [71]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])              # 3행 3열
vector = np.array([10, 20, 30]) # 1차원 배열 (1x3 처럼 간주됨)    # 1행 3열

# 자동으로 행의 크기를 맞춰서 더해줌
matrix + vector           # 모든행에 10,20,30 으로 더해짐

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [93]:
# vector가 matrix의 각 행에 더해짐

In [76]:
# 열 벡터와의 연산 (reshape 필요)
vector2 = np.array([[10], [20], [30]])
vector2

array([[10],
       [20],
       [30]])

In [77]:
matrix + vector2

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

* 유니버설 함수 (Universal Functions, ufuncs): 배열의 각 요소에 대해 연산을 수행하는 함수들입니다. 매우 빠릅니다.

In [80]:
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))       # 자연로그
print(np.sin(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]


### 기본 선형대수 연산
딥러닝은 선형대수에 기반하므로, 행렬 곱, 전치 등은 필수입니다.

In [84]:
mat_a = np.array([[1, 2], [3, 4]])
mat_b = np.array([[5, 6], [7, 8]])
mat_b

array([[5, 6],
       [7, 8]])

In [85]:
# 요소별 곱셈 (element-wise multiplication)
mat_a * mat_b

array([[ 5, 12],
       [21, 32]])

In [88]:
# 행렬 곱셈 (Matrix multiplication)
A = mat_a @ mat_b
A

array([[19, 22],
       [43, 50]])

In [89]:
# 전치 행렬 (Transpose)
A.T        # 행과 열을 바꿈

array([[19, 43],
       [22, 50]])

### 배열 형태 변경 (Reshaping)
배열의 차원이나 형태를 바꾸는 기능입니다. 데이터의 총 개수는 유지되어야 합니다.

In [90]:
arr = np.arange(12) # [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
# 3행 4열의 2차원 배열로 변경
arr.reshape(3, 4) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
# -1을 사용하면 해당 차원의 크기를 자동으로 계산
A = arr.reshape(-1, 4)      # -1로 하면 자동 
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
# 다차원 배열을 1차원으로 펼치기 (Flatten)
A.flatten()          # 1차원으로 쭉 펴줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 집계 함수 (Aggregation)
배열 전체 또는 특정 축(axis)을 기준으로 합계, 평균, 최대/최소값 등을 계산합니다.

In [107]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
print(np.sum(arr))      # 요소들의 합
print(np.mean(arr))     # 요소들의 평균
print(np.median(arr))  
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

21
3.5
3.5
6
1
1.707825127659933


In [113]:
print(np.mean(arr, axis = 0))        # 아랫방향으로 평균을 구한다
print(np.mean(arr, axis = 1))        # 오른쪽방향으로 평균을 구한다

[2.5 3.5 4.5]
[2. 5.]


# 연습문제
1. 파이썬 리스트 my_list = [10, 20, 30, 40, 50]를 사용하여 NumPy 1차원 배열 arr1d를 만드세요. 생성된 배열을 출력하세요.

In [114]:
my_list = [10, 20, 30, 40, 50]
arr1d = np.array(my_list)
arr1d

array([10, 20, 30, 40, 50])

2. 3행 4열 크기의 모든 요소가 0인 NumPy 배열 zeros_arr를 만드세요. 생성된 배열의 shape (형태)과 dtype (데이터 타입)을 출력하세요.

In [120]:
zeros_arr = np.zeros((3, 4))
print(zeros_arr.shape)
print(zeros_arr.dtype)

(3, 4)
float64


3. np.arange() 함수를 사용하여 0부터 8까지의 정수로 구성된 NumPy 배열을 만든 후, 이 배열을 3x3 크기의 2차원 배열 mat3x3으로 변형(reshape)하세요. 생성된 mat3x3 배열을 출력하세요.

In [124]:
mat3x3 = np.arange(0,9).reshape(3,3)
mat3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. 다음과 같은 2차원 배열 arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])가 주어졌습니다.
* (a) 2행 3열의 요소 (값: 6)를 인덱싱을 사용하여 추출하세요.
* (b) 마지막 두 행과 첫 두 열로 이루어진 부분 배열 ([[4, 5], [7, 8]])을 슬라이싱을 사용하여 추출하세요.

In [128]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 2])
print(arr[1:, :2])

6
[[4 5]
 [7 8]]


5. 1부터 50까지의 정수 난수(포함)로 구성된 4x5 크기의 배열 rand_arr를 만드세요. 그런 다음, 이 배열의 요소들 중에서 25보다 큰 값들만 추출하여 새로운 배열 filtered_arr를 만드세요. filtered_arr를 출력하세요.

In [130]:
rand_arr = np.random.randint(1, 51, size = (4,5))
filtered_arr = rand_arr[rand_arr>25]
filtered_arr

array([42, 39, 44, 50, 35, 48, 30, 47, 43, 32])

6. 두 개의 NumPy 배열 a = np.array([1, 2, 3]) 와 b = np.array([4, 5, 6]) 가 주어졌을 때, 두 배열의 요소별 합 (a + b)과 요소별 곱 (a * b)을 계산하여 각각 출력하세요.

In [132]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


7. 2차원 배열 matrix = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]]) 와 1차원 배열 vector = np.array([10, 20, 30]) 가 있을 때, 브로드캐스팅을 이용하여 matrix의 각 행에 vector를 더한 결과 배열 broadcast_sum을 계산하고 출력하세요.

In [134]:
matrix = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
vector = np.array([10, 20, 30])

broadcast_sum = matrix + vector
broadcast_sum

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

8. 배열 arr_sq = np.array([1, 4, 9, 16, 25]) 가 주어졌습니다.
* (a) 각 요소의 제곱근을 계산한 배열 sqrt_arr를 만드세요.
* (b) sqrt_arr 배열의 모든 요소의 평균값을 계산하여 출력하세요-.

In [136]:
arr_sq = np.array([1, 4, 9, 16, 25])
sqrt_arr = np.sqrt(arr_sq)
np.mean(sqrt_arr)

3.0

9. 두 개의 행렬 mat_a = np.array([[1, 0], [2, 1]]) 와 mat_b = np.array([[4, 1], [0, 2]]) 가 주어졌습니다.
* (a) 두 행렬의 행렬 곱을 계산하여 mat_product에 저장하세요.
* (b) 결과 행렬 mat_product의 전치(Transpose) 행렬을 구하여 출력하세요.

In [143]:
mat_a = np.array([[1, 0], [2, 1]])
mat_b = np.array([[4, 1], [0, 2]]) 

mat_product = mat_a @ mat_b
mat_product.T

array([[4, 8],
       [1, 4]])

10. 다음과 같은 3x4 배열 data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 10, 20, 30]]) 가 주어졌습니다.
* (a) 각 열(column)의 합계를 계산하여 출력하세요.
* (b) 각 행(row)의 최댓값을 계산하여 출력하세요.

In [144]:
data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 10, 20, 30]]) 
print(np.sum(data, axis = 0))
print(np.max(data, axis = 1))

[150  90 120 150]
[40 80 90]
